pipeline {
  agent any

  parameters {
    choice(name: 'SCAN_LEVEL', choices: ['quick', 'full'], description: 'Security scan depth')
    booleanParam(name: 'RUN_SECURITY_SCANS', defaultValue: true, description: 'Run Semgrep, Gitleaks, and npm audit')
  }

  environment {
    APP_NAME = 'grc-vuln-dashboard'
    DOCKER_IMAGE = "grc-vuln-dashboard:${BUILD_NUMBER}"
  }

  tools {
    nodejs 'NodeJS-26'
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

  stage('Debug Workspace') {
    steps {
      sh '''
        pwd
        ls -la
        find . -maxdepth 3 -type f | sort | head -100
        grep -R "AKIA\\|ghp_\\|dangerouslySetInnerHTML\\|eval(" -n src || true
      '''
    }
  }

  stage('Verify NodeJS') {
      steps {
        sh 'node -v'
      }
    }

  stage('Verify Docker') {
    steps {
      sh '''
        docker version
        docker compose version
      '''
    }
  }  

    stage('Install Dependencies') {
      steps {
        sh 'npm ci'
      }
    }

    stage('Build App') {
      steps {
        sh 'npm run build'
      }
    }

    stage('Prepare Scan Directories') {
      when {
        expression { return params.RUN_SECURITY_SCANS }
      }
      steps {
        sh '''
          mkdir -p scans/semgrep
          mkdir -p scans/gitleaks
          mkdir -p scans/dependency-scan
          mkdir -p scans/html
        '''
      }
    }

    stage('Semgrep SAST') {
      when {
        expression { return params.RUN_SECURITY_SCANS }
      }
      steps {
        sh '''
          mkdir -p scans/semgrep

          docker run --rm \
            -v "${WORKSPACE}:/src" \
            semgrep/semgrep \
            semgrep scan \
              --config p/javascript \
              --config p/typescript \
              --config p/react \
              --json \
              --output /src/scans/semgrep/semgrep-results.json \
              /src || true

          ls -la scans/semgrep
          cat scans/semgrep/semgrep-results.json || true
        '''
      }
    }

    stage('Gitleaks Secret Scan') {
      when {
        expression { return params.RUN_SECURITY_SCANS }
      }
      steps {
        sh '''
          mkdir -p scans/gitleaks

          docker run --rm \
            -v "${WORKSPACE}:/repo" \
            zricethezav/gitleaks:latest \
            detect \
              --source=/repo \
              --report-format json \
              --report-path /repo/scans/gitleaks/gitleaks-results.json \
              --verbose || true

          ls -la scans/gitleaks
          cat scans/gitleaks/gitleaks-results.json || true
        '''
      }
    }

    stage('Dependency Scan') {
      when {
        expression { return params.RUN_SECURITY_SCANS }
      }
      steps {
        sh '''
          npm audit --json > scans/dependency-scan/npm-audit-results.json || true
        '''
      }
    }

    stage('Docker Build') {
      steps {
        sh 'docker build -t $DOCKER_IMAGE .'
      }
    }

    stage('Generate HTML Security Report') {
      when {
        expression { return params.RUN_SECURITY_SCANS }
      }
      steps {
        sh '''
          cat > scans/html/index.html <<EOF
            <!DOCTYPE html>
            <html>
            <head>
              <title>Security Scan Results</title>
              <style>
                body { font-family: Arial, sans-serif; margin: 40px; }
                h1 { color: #222; }
                .card { border: 1px solid #ddd; padding: 16px; margin-bottom: 16px; border-radius: 8px; }
                code { background: #f4f4f4; padding: 4px; }
              </style>
            </head>
            <body>
              <h1>GRC Vulnerable Dashboard - Security Scan Results</h1>

              <div class="card">
                <h2>Semgrep SAST</h2>
                <p>Artifact: <code>scans/semgrep/semgrep-results.json</code></p>
              </div>

              <div class="card">
                <h2>Gitleaks Secret Scan</h2>
                <p>Artifact: <code>scans/gitleaks/gitleaks-results.json</code></p>
              </div>

              <div class="card">
                <h2>npm Dependency Audit</h2>
                <p>Artifact: <code>scans/dependency-scan/npm-audit-results.json</code></p>
              </div>

              <p>This report is generated by Jenkins and archived as AppSec evidence.</p>
            </body>
            </html>
            EOF
        '''
      }
    }
  }

  post {
    always {
      archiveArtifacts artifacts: 'scans/**/*', allowEmptyArchive: true

      publishHTML([
        allowMissing: true,
        alwaysLinkToLastBuild: true,
        keepAll: true,
        reportDir: 'scans/html',
        reportFiles: 'index.html',
        reportName: 'Security Scan Results'
      ])
    }
  }
}